const chefs = [
  {
    id: "1",
    name: "Leslie Alexander",
    followers: "500",
    isFollowed: false,
    imagesNum: 20,
    userImage: require("../assets/chef.png"),
    isOnline: true,
    images: [
      require("../assets/cock2.png"),
      require("../assets/cock1.png"),
      require("../assets/cock3.png"),
    ],
  },
  {
    id: "2",
    name: "Kristin Watson",
    followers: "500",
    isFollowed: true,
    imagesNum: 15,
    userImage: require("../assets/chef2.png"),
    isOnline: true,
    images: [
      require("../assets/cock1.png"),
      require("../assets/cock2.png"),
      require("../assets/cock3.png"),
    ],
  },
  {
    id: "3",
    name: "Leslie Alexander",
    followers: "500",
    isFollowed: true,
    imagesNum: 6,
    userImage: require("../assets/chef3.png"),
    isOnline: true,
    images: [
      require("../assets/cock2.png"),
      require("../assets/cock3.png"),
      require("../assets/cock1.png"),
    ],
  },
  {
    id: "4",
    name: "Kristin Watson",
    followers: "500",
    isFollowed: false,
    imagesNum: 10,
    userImage: require("../assets/chef2.png"),
    isOnline: false,
    images: [
      require("../assets/cock1.png"),
      require("../assets/cock3.png"),
      require("../assets/cock2.png"),
    ],
  },
  {
    id: "5",
    name: "Kristin Watson",
    followers: "500",
    isFollowed: false,
    imagesNum: 23,
    userImage: require("../assets/chef3.png"),
    isOnline: false,
    images: [
      require("../assets/cock3.png"),
      require("../assets/cock1.png"),
      require("../assets/cock2.png"),
    ],
  },
  {
    id: "6",
    name: "Leslie Alexander",
    followers: "500",
    isFollowed: true,
    imagesNum: 16,
    userImage: require("../assets/chef.png"),
    isOnline: true,
    images: [
      require("../assets/cock2.png"),
      require("../assets/cock3.png"),
      require("../assets/cock1.png"),
    ],
  },
  {
    id: "7",
    name: "Leslie Alexander",
    followers: "500",
    isFollowed: false,
    imagesNum: 20,
    userImage: require("../assets/chef.png"),
    isOnline: true,
    images: [
      require("../assets/cock2.png"),
      require("../assets/cock3.png"),
      require("../assets/cock1.png"),
    ],
  },
  {
    id: "8",
    name: "Kristin Watson",
    followers: "500",
    isFollowed: true,
    imagesNum: 15,
    userImage: require("../assets/chef2.png"),
    isOnline: true,
    images: [
      require("../assets/cock3.png"),
      require("../assets/cock1.png"),
      require("../assets/cock2.png"),
    ],
  },
  {
    id: "9",
    name: "Leslie Alexander",
    followers: "500",
    isFollowed: true,
    imagesNum: 6,
    userImage: require("../assets/chef3.png"),
    isOnline: true,
    images: [
      require("../assets/cock2.png"),
      require("../assets/cock3.png"),
      require("../assets/cock1.png"),
    ],
  },
  {
    id: "14",
    name: "Kristin Watson",
    followers: "500",
    isFollowed: false,
    imagesNum: 10,
    userImage: require("../assets/chef2.png"),
    isOnline: false,
    images: [
      require("../assets/cock1.png"),
      require("../assets/cock3.png"),
      require("../assets/cock2.png"),
    ],
  },
  {
    id: "15",
    name: "Kristin Watson",
    followers: "500",
    isFollowed: false,
    imagesNum: 23,
    userImage: require("../assets/chef3.png"),
    isOnline: false,
    images: [
      require("../assets/cock3.png"),
      require("../assets/cock1.png"),
      require("../assets/cock2.png"),
    ],
  },
  {
    id: "1s6",
    name: "Leslie Alexander",
    followers: "500",
    isFollowed: true,
    imagesNum: 16,
    userImage: require("../assets/chef.png"),
    isOnline: true,
    images: [
      require("../assets/cock1.png"),
      require("../assets/cock3.png"),
      require("../assets/cock2.png"),
    ],
  },
];

export default chefs;
